[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
treasury_your_wallet = "AqejyYXgr792tntPRJajpBLMvhYCTFXQWRoBzUKp6TkN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/dewey/Documents/project/Treasury/treasury-your-wallet/dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
